# Generated by Django 5.0.5 on 2024-05-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_l', models.CharField(max_length=10, verbose_name='業態カテゴリ')),
                ('name', models.CharField(max_length=30, verbose_name='業態名')),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=6, verbose_name='都道府県コード')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=10, verbose_name='店舗ID')),
                ('shop_name', models.CharField(max_length=200, verbose_name='店舗名')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='画像１URL')),
                ('comment', models.TextField(verbose_name='レビューコメント')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3, verbose_name='レビュースコア')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop_id', 'user')},
            },
        ),
    ]
