# Generated by Django 5.0.5 on 2024-05-30 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name_kana',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_image1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_image2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='station',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='station_line',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='url',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='url_mobile',
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.category', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='営業時間'),
        ),
        migrations.AddField(
            model_name='shop',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='価格帯'),
        ),
        migrations.AddField(
            model_name='shop',
            name='regular_holiday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='定休日'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='pr_long',
            field=models.TextField(blank=True, null=True, verbose_name='店舗PR'),
        ),
    ]
