# Generated by Django 5.0.5 on 2024-05-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pref',
        ),
    ]
