# Generated by Django 5.0.5 on 2024-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_shop_latitude_remove_shop_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='pr_long',
            field=models.TextField(blank=True, null=True, verbose_name='店舗紹介'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='予算'),
        ),
    ]
