# Generated by Django 5.0.5 on 2024-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_store_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
